services:
  mysql_master:
    container_name: mysql_master
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sakila
    ports:
      - "3306:3306"
    volumes:
      - ./master/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./master/data:/var/lib/mysql
 
  mysql_slave:
    container_name: mysql_salve
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sakila
    ports:
      - "3307:3306"
    volumes:
      - ./slave/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./slave/data:/var/lib/mysql
    depends_on:
      - mysql_master
