services:
  mysql_master_one:
    container_name: mysql_master_one
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: MASTEEER
    ports:
      - "3306:3306"
    volumes:
      - ./masterone/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./masterone/data:/var/lib/mysql

  mysql_master_two:
    container_name: mysql_master_two
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: MASTEEER
    ports:
      - "3307:3306"
    volumes:
      - ./mastertwo/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mastertwo/data:/var/lib/mysql
    depends_on:
      - mysql_master_one